[[bin]]
name = "River"
path = "Source/River.rs"

[build-dependencies]
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
toml = "0.8.19"

[dependencies]
Echo = { version = "0.0.1", path = "../Echo" }
async-trait = "0.1.82"
# TODO: To implement
# dashmap = "6.0.1"
futures = "0.3.30"
serde = { version = "1.0.209", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
tokio-tungstenite = "0.23.1"

[package]
autobenches = false
autobins = false
autoexamples = false
autotests = false
publish = false
default-run = "River"
description = "ğŸŒŠâ€Riverâ€â€”"
license = "MIT"
name = "River"
repository = "HTTPS://GitHub.Com/CodeEditorLand/River"
version = "0.0.1"
edition = "2021"
