[[bin]]
name = "River"
path = "Source/River.rs"

[build-dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
toml = "0.8.14"

[dependencies]
async-trait = "0.1.81"
dashmap = "6.0.1"
Echo = { version = "0.0.0", path = "../Echo" }
futures = "0.3.30"
serde = "1.0.204"
serde_json = "1.0.120"
tokio = "1.38.0"
tokio-tungstenite = "0.23.1"

[package]
autobenches = false
autobins = false
autoexamples = false
autotests = false
publish = false
default-run = "River"
description = "ğŸŒŠâ€Riverâ€â€”"
license = "MIT"
name = "River"
repository = "HTTPS://GitHub.Com/CodeEditorLand/River"
version = "0.0.0"
edition = "2021"
