[[bin]]
name = "River"
path = "Source/Library.rs"

[build-dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
toml = "0.8.14"

[dependencies]
async-trait = "0.1.80"
dashmap = "6.0.1"
echo = { version = "0.0.0" }
futures = "0.3.30"
serde = "1.0.203"
serde_json = "1.0.120"
tokio = "1.38.0"
tokio-tungstenite = "0.23.1"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name = "Library"
path = "Source/Library.rs"

[package]
autobenches = false
autobins = false
autoexamples = false
autotests = false
default-run = "River"
description = "ğŸŒŠâ€Riverâ€â€”"
license = "MIT"
name = "river"
repository = "HTTPS://GitHub.Com/CodeEditorLand/River"
version = "0.0.0"
edition = "2021"
