[[bin]]
name = "River"
path = "Source/Library.rs"

[dependencies]

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name = "Library"
path = "Source/Library.rs"

[package]
autobenches = false
autobins = false
autoexamples = false
autotests = false
default-run = "River"
description = "ğŸŒŠâ€Riverâ€â€”"
license = "MIT"
name = "river"
repository = "https://github.com/CodeEditorLand/River.git"
version = "0.0.0"
edition = "2021"
